name: Run and Time Competition Solutions

on:
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Run All Tests
      run: python run_tests.py

    - name: Time Solutions
      run: python time_solutions.py
